### ETL del archivo en crudo `movies_dataset.parquet` con las columnas de datos simples. El nuevo dataset se va a llamar `movies`

In [1]:
import pandas as pd
import ast
import os
import gc
import json

In [2]:
url = "https://github.com/FranciscoHugoLezik/Movies_data/blob/main/movies_dataset.parquet?raw=true"

movies = (
    pd.read_parquet(
        url, 
        engine="fastparquet"
        )
    )

In [3]:
movies.iloc[0]

adult                                                                False
belongs_to_collection    {'id': 10194, 'name': 'Toy Story Collection', ...
budget                                                            30000000
genres                   [{'id': 16, 'name': 'Animation'}, {'id': 35, '...
homepage                              http://toystory.disney.com/toy-story
id                                                                     862
imdb_id                                                          tt0114709
original_language                                                       en
original_title                                                   Toy Story
overview                 Led by Woody, Andy's toys live happily in his ...
popularity                                                       21.946943
poster_path                               /rhIRbceoE9lR4veEXuwCC2wARtG.jpg
production_companies        [{'name': 'Pixar Animation Studios', 'id': 3}]
production_countries     [{'iso_3166_1': 'US', 'name': 'United States o...
release_date                                                    1995-10-30
revenue                                                          373554033
runtime                                                               81.0
spoken_languages                  [{'iso_639_1': 'en', 'name': 'English'}]
status                                                            Released
tagline                                                               None
title                                                            Toy Story
video                                                                False
vote_average                                                           7.7
vote_count                                                            5415
Name: 0, dtype: object

In [4]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  object
 16  runtime                45203 non-null  object
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  object
 23  vote_count             45460 non-null  object
dtypes: object(24)
memory usage: 8.3+ MB

In [5]:
movies['id'].nunique() == len(movies)

False

In [6]:
movies.drop_duplicates(
    subset='id', 
    inplace=True)

In [7]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 45436 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45436 non-null  object
 1   belongs_to_collection  4491 non-null   object
 2   budget                 45436 non-null  object
 3   genres                 45436 non-null  object
 4   homepage               7777 non-null   object
 5   id                     45436 non-null  object
 6   imdb_id                45419 non-null  object
 7   original_language      45425 non-null  object
 8   original_title         45436 non-null  object
 9   overview               44482 non-null  object
 10  popularity             45431 non-null  object
 11  poster_path            45050 non-null  object
 12  production_companies   45433 non-null  object
 13  production_countries   45433 non-null  object
 14  release_date           45349 non-null  object
 15  revenue                45430 non-null  object
 16  runtime                45173 non-null  object
 17  spoken_languages       45430 non-null  object
 18  status                 45349 non-null  object
 19  tagline                20401 non-null  object
 20  title                  45430 non-null  object
 21  video                  45430 non-null  object
 22  vote_average           45430 non-null  object
 23  vote_count             45430 non-null  object
dtypes: object(24)
memory usage: 8.7+ MB

In [8]:
movies['id'].nunique() == len(movies)

True

In [9]:
recorte = [
    "video", 
    "imdb_id", 
    "adult", 
    "original_title", 
    "poster_path", 
    "homepage", 
    "belongs_to_collection", 
    "production_companies", 
    "production_countries", 
    "spoken_languages"
    ]

movies.drop(
    columns=recorte, 
    inplace=True)

In [10]:
set(movies.columns).isdisjoint(set(recorte))

True

In [11]:
movies.rename(
    columns={'id': 'movie_id'}, 
    inplace=True
    )

In [12]:
('movie_id' in movies.columns 
 and 'id' not in movies.columns)

True

In [13]:
nested_genres = (
    movies
    [['genres', 
      'movie_id']]
    .copy()
    )

In [14]:
movies.drop(
  columns='genres', 
  inplace=True)

In [15]:
'genres' not in movies.columns

True

In [16]:
nested_genres.iloc[0]

genres      [{'id': 16, 'name': 'Animation'}, {'id': 35, '...
movie_id                                                  862
Name: 0, dtype: object

In [17]:
nested_genres.iloc[0]['genres']

"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"

In [18]:
nested_genres.rename(
    columns={'id': 'movie_id'}, 
    inplace=True
    )

In [19]:
nested_genres.columns

Index(['genres', 'movie_id'], dtype='object')

In [20]:
nested_genres.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 45436 entries, 0 to 45465
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   genres    45436 non-null  object
 1   movie_id  45436 non-null  object
dtypes: object(2)
memory usage: 1.0+ MB

In [21]:
generos_por_pelicula = [
    {**generos, 'movie_id': row['movie_id']}
    for _, row in nested_genres.iterrows()
    for generos in ast.literal_eval(row['genres'])
]

generos = pd.DataFrame(generos_por_pelicula)

In [22]:
del nested_genres
del generos_por_pelicula
gc.collect()

990

In [23]:
generos.head()

      id       name movie_id
0     16  Animation      862
1     35     Comedy      862
2  10751     Family      862
3     12  Adventure     8844
4     14    Fantasy     8844

In [24]:
generos.drop(
    columns='id', 
    inplace=True
    )

In [25]:
generos.columns

Index(['name', 'movie_id'], dtype='object')

In [26]:
generos.rename(
    columns={'name': 'genre'}, 
    inplace=True
    )

In [27]:
generos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 91027 entries, 0 to 91026
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   genre     91027 non-null  object
 1   movie_id  91027 non-null  object
dtypes: object(2)
memory usage: 1.4+ MB

In [28]:
generos_por_pelicula = (
    generos
    .groupby('movie_id')
    .agg(lambda genre: tuple(genre))
    .reset_index()
    )

In [29]:
del generos
gc.collect()

0

In [30]:
generos_por_pelicula.head()

  movie_id                      genre
0      100            (Comedy, Crime)
1    10000            (Comedy, Drama)
2    10001  (Comedy, Science Fiction)
3   100010               (Drama, War)
4   100017                   (Drama,)

In [31]:
generos_por_pelicula.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42994 entries, 0 to 42993
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  42994 non-null  object
 1   genre     42994 non-null  object
dtypes: object(2)
memory usage: 671.9+ KB

In [32]:
generos_por_pelicula['genre'] = (
    generos_por_pelicula['genre']
    .apply(lambda x: json.dumps(x)))

In [33]:
generos_por_pelicula.head()

  movie_id                          genre
0      100            ["Comedy", "Crime"]
1    10000            ["Comedy", "Drama"]
2    10001  ["Comedy", "Science Fiction"]
3   100010               ["Drama", "War"]
4   100017                      ["Drama"]

In [34]:
generos_por_pelicula.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42994 entries, 0 to 42993
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  42994 non-null  object
 1   genre     42994 non-null  object
dtypes: object(2)
memory usage: 671.9+ KB

In [35]:
movies = pd.merge(
    movies, 
    generos_por_pelicula, 
    how='inner', 
    on='movie_id'
    )

In [36]:
del generos_por_pelicula
gc.collect()

0

In [37]:
movies.iloc[0]

budget                                                        30000000
movie_id                                                           862
original_language                                                   en
overview             Led by Woody, Andy's toys live happily in his ...
popularity                                                   21.946943
release_date                                                1995-10-30
revenue                                                      373554033
runtime                                                           81.0
status                                                        Released
tagline                                                           None
title                                                        Toy Story
vote_average                                                       7.7
vote_count                                                        5415
genre                                ["Animation", "Comedy", "Family"]
Name: 0, dtype: object

In [38]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 42994 entries, 0 to 42993
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   budget             42994 non-null  object
 1   movie_id           42994 non-null  object
 2   original_language  42984 non-null  object
 3   overview           42297 non-null  object
 4   popularity         42989 non-null  object
 5   release_date       42965 non-null  object
 6   revenue            42988 non-null  object
 7   runtime            42809 non-null  object
 8   status             42937 non-null  object
 9   tagline            20135 non-null  object
 10  title              42988 non-null  object
 11  vote_average       42988 non-null  object
 12  vote_count         42988 non-null  object
 13  genre              42994 non-null  object
dtypes: object(14)
memory usage: 4.9+ MB

In [39]:
movies.dropna(
    subset='release_date', 
    inplace=True
    )

In [40]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 42965 entries, 0 to 42993
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   budget             42965 non-null  object
 1   movie_id           42965 non-null  object
 2   original_language  42955 non-null  object
 3   overview           42271 non-null  object
 4   popularity         42963 non-null  object
 5   release_date       42965 non-null  object
 6   revenue            42962 non-null  object
 7   runtime            42786 non-null  object
 8   status             42912 non-null  object
 9   tagline            20127 non-null  object
 10  title              42962 non-null  object
 11  vote_average       42962 non-null  object
 12  vote_count         42962 non-null  object
 13  genre              42965 non-null  object
dtypes: object(14)
memory usage: 4.9+ MB

In [41]:
movies.dropna(
    subset='title', 
    inplace=True
    )

In [42]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 42962 entries, 0 to 42993
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   budget             42962 non-null  object
 1   movie_id           42962 non-null  object
 2   original_language  42952 non-null  object
 3   overview           42268 non-null  object
 4   popularity         42962 non-null  object
 5   release_date       42962 non-null  object
 6   revenue            42962 non-null  object
 7   runtime            42786 non-null  object
 8   status             42912 non-null  object
 9   tagline            20127 non-null  object
 10  title              42962 non-null  object
 11  vote_average       42962 non-null  object
 12  vote_count         42962 non-null  object
 13  genre              42962 non-null  object
dtypes: object(14)
memory usage: 4.9+ MB

In [43]:
movies['budget'] = (
    movies['budget']
    .astype('int64')
    )

movies['popularity'] = (
    movies['popularity']
    .astype('float64')
    )

movies['Fecha'] = (
    pd.to_datetime(
        movies['Fecha']))

movies['Fecha'] = (
    movies['Fecha']
    .dt.strftime('%Y-%m-%d'))

movies['revenue'] = (
    movies['revenue']
    .astype('int64')
    )

movies['runtime'] = (
    movies['runtime']
    .astype('float64')
    )

movies['vote_average'] = (
    movies['vote_average']
    .astype('float64')
    )

movies['vote_count'] = (
    movies['vote_count']
    .astype('int64')
    )

KeyError: 'Fecha'

In [63]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 42962 entries, 0 to 42993
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   budget             42962 non-null  int64
 1   movie_id           42962 non-null  object
 2   original_language  42952 non-null  object
 3   overview           42268 non-null  object
 4   popularity         42962 non-null  float64
 5   release_date       42962 non-null  object
 6   revenue            42962 non-null  int64
 7   runtime            42786 non-null  float64
 8   status             42912 non-null  object
 9   tagline            20127 non-null  object
 10  title              42962 non-null  object
 11  vote_average       42962 non-null  float64
 12  vote_count         42962 non-null  int64
 13  genre              42962 non-null  object
dtypes: float64(3), int64(3), object(8)
memory usage: 4.9+ MB

In [64]:
movies.reset_index(
    drop=True, 
    inplace=True
    )

In [65]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42962 entries, 0 to 42961
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   budget             42962 non-null  int64
 1   movie_id           42962 non-null  object
 2   original_language  42952 non-null  object
 3   overview           42268 non-null  object
 4   popularity         42962 non-null  float64
 5   release_date       42962 non-null  object
 6   revenue            42962 non-null  int64
 7   runtime            42786 non-null  float64
 8   status             42912 non-null  object
 9   tagline            20127 non-null  object
 10  title              42962 non-null  object
 11  vote_average       42962 non-null  float64
 12  vote_count         42962 non-null  int64
 13  genre              42962 non-null  object
dtypes: float64(3), int64(3), object(8)
memory usage: 4.6+ MB

In [66]:
movies['revenue'] = (
    movies['revenue']
    .fillna(0)
    )

movies['budget'] = (
    movies['budget']
    .fillna(0)
    )

In [ ]:
movies['release_year'] = (
    pd.to_datetime(
        movies['release_date']
    ).dt.year.astype(str))

In [68]:
movies.iloc[0]['release_date']

'1995-10-30'

In [69]:
movies.iloc[0]['release_year']

'1995'

In [70]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42962 entries, 0 to 42961
Data columns (total 15 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   budget             42962 non-null  int64
 1   movie_id           42962 non-null  object
 2   original_language  42952 non-null  object
 3   overview           42268 non-null  object
 4   popularity         42962 non-null  float64
 5   release_date       42962 non-null  object
 6   revenue            42962 non-null  int64
 7   runtime            42786 non-null  float64
 8   status             42912 non-null  object
 9   tagline            20127 non-null  object
 10  title              42962 non-null  object
 11  vote_average       42962 non-null  float64
 12  vote_count         42962 non-null  int64
 13  genre              42962 non-null  object
 14  release_year       42962 non-null  object
dtypes: float64(3), int64(3), object(9)
memory usage: 4.9+ MB

In [71]:
return_movie = (
    lambda row: 
        row['revenue'] / row['budget'] 
    if row['revenue'] > 0 
    and row['budget'] > 0 
    else 0
    )

movies['return'] = (
    movies
    .apply(return_movie, 
           axis=1)
    .round(2)
    )

In [72]:
con_retorno = (movies['return'] != 0).sum()
con_retorno

5302

In [73]:
sin_retorno = (movies['return'] == 0).sum()
sin_retorno

37660

In [74]:
con_retorno + sin_retorno

42962

In [75]:
current_dir = os.getcwd()

current_dir

'c:\\Users\\franc\\Desktop\\Proyecto_Peliculas\\notebooks\\ETL'

In [76]:
base_dir = (
    os.path.dirname(
        os.path.dirname(
            current_dir
            )))

base_dir

'c:\\Users\\franc\\Desktop\\Proyecto_Peliculas'

In [77]:
file_path = (
    os.path.join(
        base_dir, 
        'data', 
        'ETL', 
        'movies.parquet'
        ))

file_path

'c:\\Users\\franc\\Desktop\\Proyecto_Peliculas\\data\\ETL\\movies.parquet'

In [78]:
movies.to_parquet(file_path)

In [79]:
del movies
gc.collect()

32