# ETL del archivo en crudo `movies_dataset.parquet`

## Librerías

In [1]:
import pandas as pd
import ast
import os
import gc
import json

## Extracción

In [2]:
url = "https://github.com/FranciscoHugoLezik/Movies_data/blob/main/movies_dataset.parquet?raw=true"

movies = (
    pd.read_parquet(
        url, 
        engine="fastparquet"
        )
    )

In [3]:
movies

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,None,Toy Story,False,7.7,5415
1,False,None,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",None,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",None,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92
3,False,None,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",None,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",None,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45461,False,None,0,"[{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...",http://www.imdb.com/title/tt6209470/,439050,tt6209470,fa,رگ خواب,Rising and falling between a man and woman.,...,None,0,90.0,"[{'iso_639_1': 'fa', 'name': 'فارسی'}]",Released,Rising and falling between a man and woman,Subdue,False,4.0,1
45462,False,None,0,"[{'id': 18, 'name': 'Drama'}]",None,111109,tt2028550,tl,Siglo ng Pagluluwal,An artist struggles to finish his work while a...,...,2011-11-17,0,360.0,"[{'iso_639_1': 'tl', 'name': ''}]",Released,None,Century of Birthing,False,9.0,3
45463,False,None,0,"[{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...",None,67758,tt0303758,en,Betrayal,"When one of her hits goes wrong, a professiona...",...,2003-08-01,0,90.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,A deadly game of wits.,Betrayal,False,3.8,6
45464,False,None,0,[],None,227506,tt0008536,en,Satana likuyushchiy,"In a small town live two brothers, one a minis...",...,1917-10-21,0,87.0,[],Released,None,Satan Triumphant,False,0.0,0
45465,False,None,0,[],None,461257,tt6980792,en,Queerama,50 years after decriminalisation of homosexual...,...,2017-06-09,0,75.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,None,Queerama,False,0.0,0

Ver una fila.

In [4]:
movies.iloc[0]

adult                                                                False
belongs_to_collection    {'id': 10194, 'name': 'Toy Story Collection', ...
budget                                                            30000000
genres                   [{'id': 16, 'name': 'Animation'}, {'id': 35, '...
homepage                              http://toystory.disney.com/toy-story
id                                                                     862
imdb_id                                                          tt0114709
original_language                                                       en
original_title                                                   Toy Story
overview                 Led by Woody, Andy's toys live happily in his ...
popularity                                                       21.946943
poster_path                               /rhIRbceoE9lR4veEXuwCC2wARtG.jpg
production_companies        [{'name': 'Pixar Animation Studios', 'id': 3}]
production_countries     [{'iso_3166_1': 'US', 'name': 'United States o...
release_date                                                    1995-10-30
revenue                                                          373554033
runtime                                                               81.0
spoken_languages                  [{'iso_639_1': 'en', 'name': 'English'}]
status                                                            Released
tagline                                                               None
title                                                            Toy Story
video                                                                False
vote_average                                                           7.7
vote_count                                                            5415
Name: 0, dtype: object

Obtener una información general.

In [5]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  object
 16  runtime                45203 non-null  object
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  object
 23  vote_count             45460 non-null  object
dtypes: object(24)
memory usage: 8.3+ MB

Varias columnas tienen datos faltantes.

In [6]:
movies.isnull().sum()

adult                        0
belongs_to_collection    40972
budget                       0
genres                       0
homepage                 37684
id                           0
imdb_id                     17
original_language           11
original_title               0
overview                   954
popularity                   5
poster_path                386
production_companies         3
production_countries         3
release_date                87
revenue                      6
runtime                    263
spoken_languages             6
status                      87
tagline                  25054
title                        6
video                        6
vote_average                 6
vote_count                   6
dtype: int64

La columna 'id' esta completa.

In [7]:
movies['id'].isnull().sum()

0

La columna 'title' tiene 6 nulos. Carece de sentido una película sin título.

In [8]:
movies['title'].isnull().sum()

6

Hay duplicados

In [9]:
movies['id'].duplicated(keep='first').any()

True

In [10]:
movies['id'].duplicated(keep='first').sum()

30

## Tranformación

### Borrar duplicados en la columna 'id'

Se eliminan los duplicados.

In [11]:
movies.drop_duplicates(
    subset='id', 
    inplace=True
    )

In [12]:
movies['id'].duplicated(keep='first').any()

False

In [13]:
movies['id'].duplicated(keep='first').sum()

0

### Renombrar el nombre de la columna 'id' por 'movie_id'

Se hace esto porque para, mas adelante, poder hacer un join con los dataset 'cast.parquet' y 'crew.parquet'.

In [14]:
movies.rename(
    columns={'id': 'movie_id'}, 
    inplace=True
    )

In [15]:
'id' not in movies.columns

True

In [16]:
movies.iloc[0]['movie_id']

'862'

### Desanidar la columna 'genres'

Se crea un nuevo dataframe con las columnas 'genres' y 'movie_id'.

In [57]:
genres = (
    movies[
      [
        'genres', 
        'movie_id'
        ]
      ]
    .copy()
    )

In [30]:
genres

                                                  genres movie_id
0      [{'id': 16, 'name': 'Animation'}, {'id': 35, '...      862
1      [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...     8844
2      [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...    15602
3      [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...    31357
4                         [{'id': 35, 'name': 'Comedy'}]    11862
...                                                  ...      ...
45461  [{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...   439050
45462                      [{'id': 18, 'name': 'Drama'}]   111109
45463  [{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...    67758
45464                                                 []   227506
45465                                                 []   461257

[45436 rows x 2 columns]

Ver un dato de la columna 'genres'.

In [31]:
genres.iloc[0]['genres']

"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"

Obtener una información general.

In [32]:
genres.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 45436 entries, 0 to 45465
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   genres    45436 non-null  object
 1   movie_id  45436 non-null  object
dtypes: object(2)
memory usage: 1.0+ MB

In [38]:
genres[genres['genres'] == "[]"]

      genres movie_id
55        []   124057
83        []   188588
126       []   290157
137       []   124639
390       []   267188
...      ...      ...
45447     []    44324
45448     []   122036
45455     []    67179
45464     []   227506
45465     []   461257

[2442 rows x 2 columns]

### Desanidar la columna 'genres'

Se crea una lista de diccionarios a partir de los datos anidados de la columna 'genres' juntos a los datos de la columna 'movie_id'.

In [58]:
genres['genres'] = (
    genres['genres']
    .apply(ast.literal_eval)
    )

In [59]:
genres_en_filas = (
    genres.explode('genres')
    )

In [60]:
genres_en_columnas = (
    pd.json_normalize(
        genres_en_filas['genres']
        )
    )

In [61]:
genres = (
    genres_en_filas.drop(
        columns='genres'
        )
    .join(
        genres_en_columnas
        )
    )

In [62]:
genres

      movie_id    id       name
0          862  16.0  Animation
0          862  16.0  Animation
0          862  16.0  Animation
1         8844  35.0     Comedy
1         8844  35.0     Comedy
...        ...   ...        ...
45463    67758  18.0      Drama
45463    67758  18.0      Drama
45463    67758  18.0      Drama
45464   227506  53.0   Thriller
45465   461257  80.0      Crime

[93469 rows x 3 columns]

In [63]:
genres.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 93469 entries, 0 to 45465
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  93469 non-null  object
 1   id        92552 non-null  float64
 2   name      92552 non-null  object
dtypes: float64(1), object(2)
memory usage: 2.9+ MB

In [64]:
genres.drop(
    columns='id', 
    inplace=True
    )

In [66]:
genres.columns

Index(['movie_id', 'name'], dtype='object')

In [67]:
genres.rename(
    columns={'name': 'genre'}, 
    inplace=True
    )

In [68]:
genres.columns

Index(['movie_id', 'genre'], dtype='object')

In [69]:
innecesarias = [
    "video", 
    "imdb_id", 
    "adult", 
    "original_title", 
    "poster_path", 
    "homepage", 
    "belongs_to_collection", 
    "genres", 
    "production_companies", 
    "production_countries", 
    "spoken_languages"
    ]

movies.drop(
    columns=innecesarias, 
    inplace=True
    )

In [70]:
(
    set(movies.columns)
    .isdisjoint(
        set(innecesarias)
        )
    )

True

In [77]:
for columna in movies.columns: 
    print(columna)

budget
movie_id
original_language
overview
popularity
release_date
revenue
runtime
status
tagline
title
vote_average
vote_count

In [78]:
movies = pd.merge(
    movies, 
    genres, 
    how='inner', 
    on='movie_id'
    )

In [79]:
movies

,budget,movie_id,original_language,overview,popularity,release_date,revenue,runtime,status,tagline,title,vote_average,vote_count,genre
0,30000000,862,en,"Led by Woody, Andy's toys live happily in his ...",21.946943,1995-10-30,373554033,81.0,Released,None,Toy Story,7.7,5415,Animation
1,30000000,862,en,"Led by Woody, Andy's toys live happily in his ...",21.946943,1995-10-30,373554033,81.0,Released,None,Toy Story,7.7,5415,Animation
2,30000000,862,en,"Led by Woody, Andy's toys live happily in his ...",21.946943,1995-10-30,373554033,81.0,Released,None,Toy Story,7.7,5415,Animation
3,65000000,8844,en,When siblings Judy and Peter discover an encha...,17.015539,1995-12-15,262797249,104.0,Released,Roll the dice and unleash the excitement!,Jumanji,6.9,2413,Comedy
4,65000000,8844,en,When siblings Judy and Peter discover an encha...,17.015539,1995-12-15,262797249,104.0,Released,Roll the dice and unleash the excitement!,Jumanji,6.9,2413,Comedy
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
93464,0,67758,en,"When one of her hits goes wrong, a professiona...",0.903007,2003-08-01,0,90.0,Released,A deadly game of wits.,Betrayal,3.8,6,Drama
93465,0,67758,en,"When one of her hits goes wrong, a professiona...",0.903007,2003-08-01,0,90.0,Released,A deadly game of wits.,Betrayal,3.8,6,Drama
93466,0,67758,en,"When one of her hits goes wrong, a professiona...",0.903007,2003-08-01,0,90.0,Released,A deadly game of wits.,Betrayal,3.8,6,Drama
93467,0,227506,en,"In a small town live two brothers, one a minis...",0.003503,1917-10-21,0,87.0,Released,None,Satan Triumphant,0.0,0,Thriller
93468,0,461257,en,50 years after decriminalisation of homosexual...,0.163015,2017-06-09,0,75.0,Released,None,Queerama,0.0,0,Crime

In [80]:
movies.iloc[0]

budget                                                        30000000
movie_id                                                           862
original_language                                                   en
overview             Led by Woody, Andy's toys live happily in his ...
popularity                                                   21.946943
release_date                                                1995-10-30
revenue                                                      373554033
runtime                                                           81.0
status                                                        Released
tagline                                                           None
title                                                        Toy Story
vote_average                                                       7.7
vote_count                                                        5415
genre                                                        Animation
Name: 0, dtype: object

In [81]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 93469 entries, 0 to 93468
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   budget             93469 non-null  object
 1   movie_id           93469 non-null  object
 2   original_language  93452 non-null  object
 3   overview           92139 non-null  object
 4   popularity         93452 non-null  object
 5   release_date       93353 non-null  object
 6   revenue            93448 non-null  object
 7   runtime            93115 non-null  object
 8   status             93323 non-null  object
 9   tagline            46773 non-null  object
 10  title              93448 non-null  object
 11  vote_average       93448 non-null  object
 12  vote_count         93448 non-null  object
 13  genre              92552 non-null  object
dtypes: object(14)
memory usage: 10.7+ MB

In [82]:
movies.isnull().sum()

budget                   0
movie_id                 0
original_language       17
overview              1330
popularity              17
release_date           116
revenue                 21
runtime                354
status                 146
tagline              46696
title                   21
vote_average            21
vote_count              21
genre                  917
dtype: int64

In [84]:
movies['release_date'].isnull().sum()

116

In [85]:
movies.dropna(
    subset='release_date', 
    inplace=True
    )

In [86]:
movies['release_date'].isnull().sum()

0

In [87]:
movies['title'].isnull().sum()

12

In [88]:
movies.dropna(
    subset='title', 
    inplace=True
    )

In [89]:
movies['title'].isnull().sum()

0

In [90]:
movies.dtypes

budget               object
movie_id             object
original_language    object
overview             object
popularity           object
release_date         object
revenue              object
runtime              object
status               object
tagline              object
title                object
vote_average         object
vote_count           object
genre                object
dtype: object

In [91]:
movies['budget'] = (
    movies['budget']
    .astype('int64')
    )

In [92]:
movies['popularity'] = (
    movies['popularity']
    .astype('float64')
    )

In [93]:
movies['release_date'] = (
    pd.to_datetime(
        movies['release_date']
        )
    .dt.strftime(
        '%Y-%m-%d'
        )
    )

In [ ]:
movies.iloc[0]['release_date']

In [94]:
movies['revenue'] = (
    movies['revenue']
    .astype('int64')
    )

In [95]:
movies['runtime'] = (
    movies['runtime']
    .astype('float64')
    )

In [96]:
movies['vote_average'] = (
    movies['vote_average']
    .astype('float64')
    )

In [97]:
movies['vote_count'] = (
    movies['vote_count']
    .astype('int64')
    )

In [98]:
movies.dtypes

budget                 int64
movie_id              object
original_language     object
overview              object
popularity           float64
release_date          object
revenue                int64
runtime              float64
status                object
tagline               object
title                 object
vote_average         float64
vote_count             int64
genre                 object
dtype: object

In [99]:
movies.index

Int64Index([    0,     1,     2,     3,     4,     5,     6,     7,     8,
                9,
            ...
            93457, 93458, 93459, 93460, 93463, 93464, 93465, 93466, 93467,
            93468],
           dtype='int64', length=93341)

In [101]:
movies.reset_index(
    drop=True, 
    inplace=True
    )

In [102]:
movies.index

RangeIndex(start=0, stop=93341, step=1)

In [106]:
(movies['revenue']
 .isnull()
 .sum())

0

In [104]:
movies['revenue'] = (
    movies['revenue']
    .fillna(0)
    )

In [107]:
(movies['budget']
 .isnull()
 .sum())

0

In [108]:
movies['budget'] = (
    movies['budget']
    .fillna(0)
    )

In [109]:
movies['release_year'] = (
    pd.to_datetime(
        movies['release_date']
    )
    .dt.year.astype(str)
    )

In [110]:
movies.iloc[0]['release_date']

'1995-10-30'

In [111]:
movies.iloc[0]['release_year']

'1995'

In [116]:
movies['revenue'].value_counts()[0]

74857

In [117]:
movies['budget'].value_counts()[0]

71466

In [118]:
return_movie = (
    lambda row: 
        row['revenue'] 
        / row['budget'] 
    if row['revenue'] > 0 
    and row['budget'] > 0 
    else 0
    )

In [119]:
movies['return'] = (
    movies
    .apply(return_movie, 
           axis=1)
    .round(2)
    )

In [120]:
movies['return'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 93341 entries, 0 to 93340
Series name: return
Non-Null Count  Dtype
--------------  -----
93341 non-null  float64
dtypes: float64(1)
memory usage: 729.4 KB

In [121]:
con_retorno = (movies['return'] != 0).sum()
con_retorno

13839

In [122]:
sin_retorno = (movies['return'] == 0).sum()
sin_retorno

79502

In [123]:
retornos = con_retorno + sin_retorno

retornos == len(movies['return'])

True

In [124]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93341 entries, 0 to 93340
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   budget             93341 non-null  int64
 1   movie_id           93341 non-null  object
 2   original_language  93324 non-null  object
 3   overview           92025 non-null  object
 4   popularity         93341 non-null  float64
 5   release_date       93341 non-null  object
 6   revenue            93341 non-null  int64
 7   runtime            93020 non-null  float64
 8   status             93217 non-null  object
 9   tagline            46753 non-null  object
 10  title              93341 non-null  object
 11  vote_average       93341 non-null  float64
 12  vote_count         93341 non-null  int64
 13  genre              92427 non-null  object
 14  release_year       93341 non-null  object
 15  return             93341 non-null  float64
dtypes: float64(4), int64(3), object(9)
memory usage: 11.4+ MB

## Carga

In [126]:
directorio_actual = (
    os.getcwd()
    )
directorio_actual

'c:\\Users\\franc\\Desktop\\Proyecto_Peliculas\\notebooks\\ETL'

In [127]:
directorio_del_proyecto = (
    os.path.dirname(
        os.path.dirname(
            directorio_actual
            )
        )
    )
directorio_del_proyecto

'c:\\Users\\franc\\Desktop\\Proyecto_Peliculas'

In [128]:
directorio_a_exportar = (
    os.path.join(
        directorio_del_proyecto, 
        'data', 
        'ETL', 
        'movies.parquet'
        )
    )
directorio_a_exportar

'c:\\Users\\franc\\Desktop\\Proyecto_Peliculas\\data\\ETL\\movies.parquet'

In [129]:
movies.to_parquet(
    directorio_a_exportar
    )

In [130]:
del movies
gc.collect()

1443