# ETL del archivo en crudo `movies_dataset.parquet`

## Librerías

In [139]:
import os
import ast
import gc

import pandas as pd

## Extracción

In [140]:
url = "https://github.com/FranciscoHugoLezik/Movies_data/blob/main/movies_dataset.parquet?raw=true"

movies = pd.read_parquet(
    url, 
    engine="fastparquet"
    )

La columna 'id' esta completa.

In [141]:
movies['id'].isnull().sum()

0

## Tranformación

### Borrar duplicados en la columna 'id'

Hay duplicados.

In [142]:
movies['id'].duplicated(
    keep='first'
    ).sum()

30

Se eliminan los duplicados.

In [143]:
movies.drop_duplicates(
    subset='id', 
    inplace=True
    )

Hay valores únicos.

In [144]:
movies['id'].duplicated(
    keep='first'
    ).sum()

0

### Renombrar el nombre de la columna 'id' por 'movie_id'

Se hace esto porque para, mas adelante, poder hacer un join con los dataset 'cast.parquet' y 'crew.parquet'.

In [145]:
movies.rename(
    columns={'id': 'movie_id'}, 
    inplace=True
    )

In [146]:
'id' not in movies.columns

True

In [147]:
'movie_id' in movies.columns

True

### Crear y explorar el dataframe 'genres'

Se crea un nuevo dataframe con las columnas 'genres' y 'movie_id'.

In [148]:
genres = movies[[
  'genres', 
  'movie_id'
  ]].copy()

Se explora el dataframe.

In [149]:
genres

                                                  genres movie_id
0      [{'id': 16, 'name': 'Animation'}, {'id': 35, '...      862
1      [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...     8844
2      [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...    15602
3      [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...    31357
4                         [{'id': 35, 'name': 'Comedy'}]    11862
...                                                  ...      ...
45461  [{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...   439050
45462                      [{'id': 18, 'name': 'Drama'}]   111109
45463  [{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...    67758
45464                                                 []   227506
45465                                                 []   461257

[45436 rows x 2 columns]

Ver un dato de la columna 'genres' de la primera fila.

In [150]:
genres.iloc[0]['genres']

"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"

Hay listas vacías. Se van a conservar para mantener los datos de las otras columnas al hacer un merge con el dataframe 'movies'.

In [151]:
genres[
    genres['genres'] == "[]"
    ]

      genres movie_id
55        []   124057
83        []   188588
126       []   290157
137       []   124639
390       []   267188
...      ...      ...
45447     []    44324
45448     []   122036
45455     []    67179
45464     []   227506
45465     []   461257

[2442 rows x 2 columns]

### Desanidar la columna 'genres'

Se convierte a las cadenas en listas de diccionarios.

In [152]:
genres['genres'] = (
    genres['genres']
    .apply(ast.literal_eval)
    )

Se separan los elementos de las listas en filas.

In [153]:
genres_en_filas = (
    genres.explode('genres')
    )

Se convierten las llaves en columnas.

In [154]:
genres_en_columnas = (
    pd.json_normalize(
        genres_en_filas['genres']
        )
    )

### Crear dataframe 'genres'

Se crea un dataframe con la columna 'movie_id' junto con las nuevas columnas.

In [155]:
genres = genres_en_filas.drop(
    columns='genres'
    ).join(
        genres_en_columnas
        )

In [156]:
del genres_en_filas
del genres_en_columnas
gc.collect()

1097

In [157]:
genres

      movie_id    id       name
0          862  16.0  Animation
0          862  16.0  Animation
0          862  16.0  Animation
1         8844  35.0     Comedy
1         8844  35.0     Comedy
...        ...   ...        ...
45463    67758  18.0      Drama
45463    67758  18.0      Drama
45463    67758  18.0      Drama
45464   227506  53.0   Thriller
45465   461257  80.0      Crime

[93469 rows x 3 columns]

Se agrupa por la columna 'movie_id'

In [158]:
genres = genres.groupby(
    'movie_id'
    ).agg(
        {'name': list}
        ).reset_index()

Se explora el dataframe.

In [159]:
genres

      movie_id                            name
0          100                [Comedy, Comedy]
1        10000              [Mystery, Mystery]
2        10001                [Action, Action]
3       100010              [Mystery, Mystery]
4       100017                         [Drama]
...        ...                             ...
45431    99946                         [Music]
45432     9995  [Thriller, Thriller, Thriller]
45433     9997    [Drama, Drama, Drama, Drama]
45434    99977                       [Romance]
45435     9999                  [Drama, Drama]

[45436 rows x 2 columns]

Primera fila.

In [160]:
genres.iloc[0]

movie_id                 100
name        [Comedy, Comedy]
Name: 0, dtype: object

### Renombrar la columna 'name' de 'genres'

Se renombra la columna 'name' por 'genres'.

In [161]:
genres.rename(
    columns={'name': 'genres'}, 
    inplace=True
    )

La columna fue renombrada.

In [162]:
genres.columns

Index(['movie_id', 'genres'], dtype='object')

### Eliminar las columnas innecesarias de 'movies'

Columnas innecesarias.

In [163]:
innecesarias = [
    "video", 
    "imdb_id", 
    "adult", 
    "original_title", 
    "poster_path", 
    "homepage", 
    "belongs_to_collection", 
    "genres", 
    "production_companies", 
    "production_countries", 
    "spoken_languages"
    ]

Las columnas innecesarias son eliminadas.

In [164]:
movies.drop(
    columns=innecesarias, 
    inplace=True
    )

Las columnas innecesarias estan eliminadas.

In [165]:
set(movies.columns).isdisjoint(
    set(innecesarias)
    )

True

### Unir 'movies' con 'genres'

In [166]:
movies = pd.merge(
    movies, 
    genres, 
    how='inner', 
    on='movie_id'
    )

In [167]:
del genres
gc.collect()

0

### Eliminar los nulos de la columna 'title'

Hay nulos en la columna 'release_date'.

In [168]:
movies['title'].isnull().sum()

6

Se eliminan los nulos.

In [169]:
movies.dropna(
    subset='title', 
    inplace=True
    )

Los nulos están eliminados.

In [170]:
movies['release_date'].isnull().sum()

84

### Eliminar los nulos de la columna 'release_date'

Hay nulos en la columna 'release_date'.

In [171]:
movies['release_date'].isnull().sum()

84

Se eliminan los nulos.

In [172]:
movies.dropna(
    subset='release_date', 
    inplace=True
    )

Los nulos están eliminados.

In [173]:
movies['release_date'].isnull().sum()

0

### Cambiar los tipos de algunas columnas

Todas las columnas tienen el tipo object.

In [174]:
movies.dtypes

budget               object
movie_id             object
original_language    object
overview             object
popularity           object
release_date         object
revenue              object
runtime              object
status               object
tagline              object
title                object
vote_average         object
vote_count           object
genres               object
dtype: object

* Columna 'budget'.

In [175]:
movies['budget'].dtype

dtype('O')

In [176]:
movies['budget'] = (
    movies['budget']
    .astype('int64')
    )

In [177]:
movies['budget'].dtype

dtype('int64')

* Columna 'popularity'.

In [178]:
movies['popularity'].dtype

dtype('O')

In [179]:
movies['popularity'] = (
    movies['popularity']
    .astype('float64')
    )

In [180]:
movies['popularity'].dtype

dtype('float64')

* Columna 'release_date'.

In [181]:
movies['release_date'].dtype

dtype('O')

In [182]:
movies['release_date'] = (
    pd.to_datetime(
        movies['release_date']
        )
    .dt.strftime(
        '%Y-%m-%d'
        )
    )

In [183]:
movies['release_date'].dtype

dtype('O')

In [184]:
movies.iloc[0]['release_date']

'1995-10-30'

* Columna 'revenue'.

In [185]:
movies['revenue'].dtype

dtype('O')

In [186]:
movies['revenue'] = (
    movies['revenue']
    .astype('int64')
    )

In [187]:
movies['revenue'].dtype

dtype('int64')

* Columna 'runtime'.

In [188]:
movies['runtime'].dtype

dtype('O')

In [189]:
movies['runtime'] = (
    movies['runtime']
    .astype('float64')
    )

In [190]:
movies['runtime'].dtype

dtype('float64')

* Columna 'vote_average'.

In [191]:
movies['vote_average'].dtype

dtype('O')

In [192]:
movies['vote_average'] = (
    movies['vote_average']
    .astype('float64')
    )

In [193]:
movies['vote_average'].dtype

dtype('float64')

* Columna 'vote_count'.

In [194]:
movies['vote_count'].dtype

dtype('O')

In [195]:
movies['vote_count'] = (
    movies['vote_count']
    .astype('int64')
    )

In [196]:
movies['vote_count'].dtype

dtype('int64')

Tipos de las columnas.

In [197]:
movies.dtypes

budget                 int64
movie_id              object
original_language     object
overview              object
popularity           float64
release_date          object
revenue                int64
runtime              float64
status                object
tagline               object
title                 object
vote_average         float64
vote_count             int64
genres                object
dtype: object

### Rellenar con cero los valores nulos en las columnas 'revenue' y 'budget'

Columna 'revenue'.

In [198]:
movies['revenue'].isnull().sum()

0

In [199]:
movies['revenue'] = (
    movies['revenue']
    .fillna(0)
    )

Columna 'budget'.

In [200]:
(movies['budget']
 .isnull()
 .sum())

0

In [201]:
movies['budget'] = (
    movies['budget']
    .fillna(0)
    )

### Eliminar los nulos de la columna 'release_date'

Hay nulos en la columna 'release_date'.

In [202]:
movies['release_date'].isnull().sum()

0

Se eliminan los nulos.

In [203]:
movies.dropna(
    subset='release_date', 
    inplace=True
    )

Los nulos están eliminados.

In [204]:
movies['release_date'].isnull().sum()

0

### Crear la columna 'release_year'

Se extrae el año de la columna 'release_date' en la nueva columna 'release_year'.

In [205]:
movies['release_year'] = (
    pd.to_datetime(
        movies['release_date']
    )
    .dt.year.astype(str)
    )

El año fue extraído correctamente.

In [206]:
movies.iloc[0]['release_year']

'1995'

### Crear la columna 'return'

Gran parte de los datos son cero en las columnas 'revenue' y 'budget'.

In [207]:
movies['revenue'].value_counts()[0]

37949

In [208]:
movies['budget'].value_counts()[0]

36470

Se crea una variable que divide el valor de la columna 'revenue' por el valor de la columna 'budget' siempre que ambos valores sean mayores a cero.

In [209]:
return_movie = (
    lambda row: 
        row['revenue'] 
        / row['budget'] 
    if row['revenue'] > 0 
    and row['budget'] > 0 
    else 0
    )

Se crea la columna 'return' asignandole la anterior operación.

In [210]:
movies['return'] = (
    movies
    .apply(return_movie, 
           axis=1)
    .round(2)
    )

La columna 'return' fue creada.

In [211]:
'return' in movies.columns

True

### Resetear el índice

El último índice es mayor a la cantidad de filas.

In [212]:
movies.index

Int64Index([    0,     1,     2,     3,     4,     5,     6,     7,     8,
                9,
            ...
            45425, 45426, 45427, 45428, 45429, 45430, 45432, 45433, 45434,
            45435],
           dtype='int64', length=45346)

Se resetea el índice.

In [213]:
movies.reset_index(
    drop=True, 
    inplace=True
    )

El índice es igual a la cantidad de filas - 1.

In [214]:
movies.index

RangeIndex(start=0, stop=45346, step=1)

### Última revisión

In [215]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45346 entries, 0 to 45345
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   budget             45346 non-null  int64
 1   movie_id           45346 non-null  object
 2   original_language  45335 non-null  object
 3   overview           44405 non-null  object
 4   popularity         45346 non-null  float64
 5   release_date       45346 non-null  object
 6   revenue            45346 non-null  int64
 7   runtime            45100 non-null  float64
 8   status             45266 non-null  object
 9   tagline            20387 non-null  object
 10  title              45346 non-null  object
 11  vote_average       45346 non-null  float64
 12  vote_count         45346 non-null  int64
 13  genres             45346 non-null  object
 14  release_year       45346 non-null  object
 15  return             45346 non-null  float64
dtypes: float64(4), int64(3), object(9)
memory usage: 5.5+ MB

## Carga

In [216]:
ruta_actual = os.getcwd()
ruta_actual

'c:\\Users\\franc\\Desktop\\Proyecto_Peliculas\\notebooks\\ETL'

In [217]:
ruta_del_proyecto = os.path.dirname(
    os.path.dirname(
        ruta_actual
        )
    )
ruta_del_proyecto

'c:\\Users\\franc\\Desktop\\Proyecto_Peliculas'

In [218]:
ruta_a_exportar = os.path.join(
    ruta_del_proyecto, 
    'data', 
    'ETL', 
    'movies.parquet'
    )
ruta_a_exportar

'c:\\Users\\franc\\Desktop\\Proyecto_Peliculas\\data\\ETL\\movies.parquet'

In [219]:
movies.to_parquet(
    ruta_a_exportar
    )

In [220]:
del movies
gc.collect()

96