# ETL del dataset, sin procesar, `movies_dataset.parquet`

## Librerías

Librerías nativas.

In [285]:
import os
import ast
import gc

Librerías instaladas.

In [286]:
import pandas as pd

## Extracción

Importación del dataset, sin procesar, `movies_dataset.parquet`.

In [287]:
url = "https://github.com/FranciscoHugoLezik/Movies_data/blob/main/movies_dataset.parquet?raw=true"

movies = pd.read_parquet(
    url, 
    engine="fastparquet"
    )

Se explora el dataframe.

In [288]:
movies.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,None,Toy Story,False,7.7,5415
1,False,None,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",None,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",None,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92
3,False,None,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",None,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",None,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173

Obtener información general.

In [289]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45466 entries, 0 to 45465
Data columns (total 24 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   adult                  45466 non-null  object
 1   belongs_to_collection  4494 non-null   object
 2   budget                 45466 non-null  object
 3   genres                 45466 non-null  object
 4   homepage               7782 non-null   object
 5   id                     45466 non-null  object
 6   imdb_id                45449 non-null  object
 7   original_language      45455 non-null  object
 8   original_title         45466 non-null  object
 9   overview               44512 non-null  object
 10  popularity             45461 non-null  object
 11  poster_path            45080 non-null  object
 12  production_companies   45463 non-null  object
 13  production_countries   45463 non-null  object
 14  release_date           45379 non-null  object
 15  revenue                45460 non-null  object
 16  runtime                45203 non-null  object
 17  spoken_languages       45460 non-null  object
 18  status                 45379 non-null  object
 19  tagline                20412 non-null  object
 20  title                  45460 non-null  object
 21  video                  45460 non-null  object
 22  vote_average           45460 non-null  object
 23  vote_count             45460 non-null  object
dtypes: object(24)
memory usage: 8.3+ MB

La columna 'id' esta completa.

In [290]:
movies['id'].isnull().sum()

0

## Tranformación

### Borrar duplicados en la columna 'id'

Hay valores duplicados en la columna 'id'.

In [291]:
movies['id'].duplicated(
    keep='first').sum()

30

Se eliminan los duplicados.

In [292]:
movies.drop_duplicates(
    subset='id', 
    inplace=True
    )

Hay valores únicos.

In [293]:
movies['id'].duplicated(
    keep='first').sum()

0

### Renombrar la columna 'id' por 'movie_id'

Se hace esto porque para, mas adelante, poder hacer un join con los dataset 'cast.parquet' y 'crew.parquet'.

In [294]:
movies.rename(
    columns={'id': 'movie_id'}, 
    inplace=True
    )

Se cambio el nombre.

In [295]:
'id' not in movies.columns

True

In [296]:
'movie_id' in movies.columns

True

### Extraer la columna 'genres'

Se crea un nuevo dataframe con las columnas 'genres' y 'movie_id'.

In [297]:
genres = movies[[
  'genres', 
  'movie_id'
  ]].copy()

Se explora el dataframe.

In [298]:
genres

                                                  genres movie_id
0      [{'id': 16, 'name': 'Animation'}, {'id': 35, '...      862
1      [{'id': 12, 'name': 'Adventure'}, {'id': 14, '...     8844
2      [{'id': 10749, 'name': 'Romance'}, {'id': 35, ...    15602
3      [{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...    31357
4                         [{'id': 35, 'name': 'Comedy'}]    11862
...                                                  ...      ...
45461  [{'id': 18, 'name': 'Drama'}, {'id': 10751, 'n...   439050
45462                      [{'id': 18, 'name': 'Drama'}]   111109
45463  [{'id': 28, 'name': 'Action'}, {'id': 18, 'nam...    67758
45464                                                 []   227506
45465                                                 []   461257

[45436 rows x 2 columns]

Valor en la columna 'genres' de la primera fila. Es una cadena con la forma de una lista de diccionarios.

In [299]:
genres['genres'].iloc[0]

"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"

La columna 'genres' esta completa.

In [300]:
genres['genres'].isnull().sum()

0

Hay listas vacías.

In [301]:
genres[genres['genres'] == '[]']

      genres movie_id
55        []   124057
83        []   188588
126       []   290157
137       []   124639
390       []   267188
...      ...      ...
45447     []    44324
45448     []   122036
45455     []    67179
45464     []   227506
45465     []   461257

[2442 rows x 2 columns]

### Desanidar la columna 'genres'

Se convierte a las cadenas en listas de diccionarios.

In [302]:
genres['genres'] = genres['genres'].apply(
    ast.literal_eval)

Se separan los elementos de las listas en filas.

In [303]:
genres_en_filas = genres.explode('genres')

Se explora el dataframe.

In [304]:
genres_en_filas

                                genres movie_id
0      {'id': 16, 'name': 'Animation'}      862
0         {'id': 35, 'name': 'Comedy'}      862
0      {'id': 10751, 'name': 'Family'}      862
1      {'id': 12, 'name': 'Adventure'}     8844
1        {'id': 14, 'name': 'Fantasy'}     8844
...                                ...      ...
45463     {'id': 28, 'name': 'Action'}    67758
45463      {'id': 18, 'name': 'Drama'}    67758
45463   {'id': 53, 'name': 'Thriller'}    67758
45464                              NaN   227506
45465                              NaN   461257

[93469 rows x 2 columns]

Se convierten las llaves en columnas.

In [305]:
genres_en_columnas = pd.json_normalize(
    genres_en_filas['genres'])

Se explora el dataframe.

In [306]:
genres_en_columnas

            id       name
0         16.0  Animation
1         35.0     Comedy
2      10751.0     Family
3         12.0  Adventure
4         14.0    Fantasy
...        ...        ...
93464     28.0     Action
93465     18.0      Drama
93466     53.0   Thriller
93467      NaN        NaN
93468      NaN        NaN

[93469 rows x 2 columns]

### Reemplazar nulos de la columna 'name'

Hay nulos.

In [307]:
genres_en_columnas['name'].isnull().sum()

2442

Se reemplazan los nulos de la columna 'name' con la palabra 'Unknown'.

In [308]:
genres_en_columnas['name'].fillna('Unknown', inplace=True)

Nulos reemplazados.

In [309]:
genres_en_columnas['name'].isnull().sum()

0

### Crear dataframe 'genres' con nuevas columnas

Se crea un dataframe con la columna 'movie_id' junto con las nuevas columnas.

Se agrega la columna de 'movie_id' del dataframe 'genres_en_filas' para poder unirla con el dataframe genres_en_columnas. Esto es para mantener la relacion con los valores de movie_id de 'genres_en_filas' con las columnas de 'genres_en_columnas'.

In [310]:
genres = genres_en_filas.drop(
    columns='genres')

Se elimina el dataframe 'genres_en_filas' para liberar memoria.

In [311]:
del genres_en_filas
gc.collect()

660

Se explora el dataframe. Hay indices repetidos.

In [312]:
genres

      movie_id
0          862
0          862
0          862
1         8844
1         8844
...        ...
45463    67758
45463    67758
45463    67758
45464   227506
45465   461257

[93469 rows x 1 columns]

Se resetea el índice.

In [313]:
genres.reset_index(drop=True, inplace=True)

Se explora para comprobar.

In [314]:
genres

      movie_id
0          862
1          862
2          862
3         8844
4         8844
...        ...
93464    67758
93465    67758
93466    67758
93467   227506
93468   461257

[93469 rows x 1 columns]

Se concatena el dataframe 'genres' con el dataframe 'genres_en_columnas' ya que las filas guardan relación.

In [315]:
genres = pd.concat([genres, genres_en_columnas], axis=1)

Se elimina el dataframe 'genres_en_columnas' para liberar memoria.

In [316]:
del genres_en_columnas
gc.collect()

0

Se explora el dataframe.

In [317]:
genres

      movie_id       id       name
0          862     16.0  Animation
1          862     35.0     Comedy
2          862  10751.0     Family
3         8844     12.0  Adventure
4         8844     14.0    Fantasy
...        ...      ...        ...
93464    67758     28.0     Action
93465    67758     18.0      Drama
93466    67758     53.0   Thriller
93467   227506      NaN    Unknown
93468   461257      NaN    Unknown

[93469 rows x 3 columns]

Se obtiene una información general.

In [318]:
genres.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 93469 entries, 0 to 93468
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  93469 non-null  object
 1   id        91027 non-null  float64
 2   name      93469 non-null  object
dtypes: float64(1), object(2)
memory usage: 2.1+ MB

Se agrupa por la columna 'movie_id'

In [319]:
genres = genres.groupby('movie_id').agg(
    {'name': list}).reset_index()

Se explora el dataframe.

In [320]:
genres

      movie_id                                        name
0          100                             [Comedy, Crime]
1        10000                             [Comedy, Drama]
2        10001                   [Comedy, Science Fiction]
3       100010                                [Drama, War]
4       100017                                     [Drama]
...        ...                                         ...
45431    99946                                    [Comedy]
45432     9995                      [Action, Crime, Drama]
45433     9997  [Fantasy, Horror, Action, Science Fiction]
45434    99977                                    [Comedy]
45435     9999                              [Crime, Drama]

[45436 rows x 2 columns]

Primera fila.

In [321]:
genres.iloc[0]

movie_id                100
name        [Comedy, Crime]
Name: 0, dtype: object

### Renombrar la columna 'name'

Se renombra la columna 'name' por 'genres'.

In [322]:
genres.rename(
    columns={'name': 'genres'}, 
    inplace=True
    )

Se cambio el nombre.

In [323]:
genres.columns

Index(['movie_id', 'genres'], dtype='object')

### Eliminar las columnas innecesarias de 'movies'

Se van a eliminar columnas que no aportan a los objetivos del proyecto.

Columnas innecesarias.

In [324]:
innecesarias = [
    "video", 
    "imdb_id", 
    "adult", 
    "original_title", 
    "poster_path", 
    "homepage", 
    "belongs_to_collection", 
    "genres", 
    "production_companies", 
    "production_countries", 
    "spoken_languages"
    ]

Las columnas innecesarias son eliminadas.

In [325]:
movies.drop(
    columns=innecesarias, 
    inplace=True
    )

Las columnas innecesarias estan eliminadas.

In [326]:
set(movies.columns).isdisjoint(set(innecesarias))

True

Se ven las columnas que quedan.

In [327]:
for columna in movies.columns:
    print(columna)

budget
movie_id
original_language
overview
popularity
release_date
revenue
runtime
status
tagline
title
vote_average
vote_count

### Unir 'movies' con 'genres'

In [328]:
movies = pd.merge(
    movies, 
    genres, 
    how='inner', 
    on='movie_id'
    )

Se elimina el dataframe 'genres' para liberar memoria.

In [329]:
del genres
gc.collect()

0

Se explora el dataframe.

In [330]:
movies

,budget,movie_id,original_language,overview,popularity,release_date,revenue,runtime,status,tagline,title,vote_average,vote_count,genres
0,30000000,862,en,"Led by Woody, Andy's toys live happily in his ...",21.946943,1995-10-30,373554033,81.0,Released,None,Toy Story,7.7,5415,"[Animation, Comedy, Family]"
1,65000000,8844,en,When siblings Judy and Peter discover an encha...,17.015539,1995-12-15,262797249,104.0,Released,Roll the dice and unleash the excitement!,Jumanji,6.9,2413,"[Adventure, Fantasy, Family]"
2,0,15602,en,A family wedding reignites the ancient feud be...,11.7129,1995-12-22,0,101.0,Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,6.5,92,"[Romance, Comedy]"
3,16000000,31357,en,"Cheated on, mistreated and stepped on, the wom...",3.859495,1995-12-22,81452156,127.0,Released,Friends are the people who let you be yourself...,Waiting to Exhale,6.1,34,"[Comedy, Drama, Romance]"
4,0,11862,en,Just when George Banks has recovered from his ...,8.387519,1995-02-10,76578911,106.0,Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,5.7,173,[Comedy]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45431,0,439050,fa,Rising and falling between a man and woman.,0.072051,None,0,90.0,Released,Rising and falling between a man and woman,Subdue,4.0,1,"[Drama, Family]"
45432,0,111109,tl,An artist struggles to finish his work while a...,0.178241,2011-11-17,0,360.0,Released,None,Century of Birthing,9.0,3,[Drama]
45433,0,67758,en,"When one of her hits goes wrong, a professiona...",0.903007,2003-08-01,0,90.0,Released,A deadly game of wits.,Betrayal,3.8,6,"[Action, Drama, Thriller]"
45434,0,227506,en,"In a small town live two brothers, one a minis...",0.003503,1917-10-21,0,87.0,Released,None,Satan Triumphant,0.0,0,[Unknown]
45435,0,461257,en,50 years after decriminalisation of homosexual...,0.163015,2017-06-09,0,75.0,Released,None,Queerama,0.0,0,[Unknown]

Se obtiene una información general.

In [331]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 45436 entries, 0 to 45435
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   budget             45436 non-null  object
 1   movie_id           45436 non-null  object
 2   original_language  45425 non-null  object
 3   overview           44482 non-null  object
 4   popularity         45431 non-null  object
 5   release_date       45349 non-null  object
 6   revenue            45430 non-null  object
 7   runtime            45173 non-null  object
 8   status             45349 non-null  object
 9   tagline            20401 non-null  object
 10  title              45430 non-null  object
 11  vote_average       45430 non-null  object
 12  vote_count         45430 non-null  object
 13  genres             45436 non-null  object
dtypes: object(14)
memory usage: 5.2+ MB

### Eliminar los nulos de la columna 'title'

Hay nulos en la columna 'title'.

In [332]:
movies['title'].isnull().sum()

6

Se eliminan los nulos.

In [333]:
movies.dropna(
    subset='title', 
    inplace=True
    )

Los nulos están eliminados.

In [334]:
movies['title'].isnull().sum()

0

### Eliminar nulos en la columna 'release_date'

Hay nulos en la columna 'release_date'.

In [335]:
movies['release_date'].isnull().sum()

84

Se eliminan los nulos.

In [336]:
movies.dropna(
    subset='release_date', 
    inplace=True
    )

Los nulos están eliminados.

In [337]:
movies['release_date'].isnull().sum()

0

### Dar formato AAAA-mm-dd a la columna 'release_date'

Se asegura que todas las fechas tengan el formato deseado:

In [338]:
movies['release_date'] = pd.to_datetime(
    movies['release_date']
    ).dt.strftime(
        '%Y-%m-%d'
        )

### Cambiar los tipos de algunas columnas

Se cambian porque se van a hacer operaciones numericas con varias columnas y una columna es de tipo fecha.

Tipos de las columnas.

In [339]:
movies.dtypes

budget               object
movie_id             object
original_language    object
overview             object
popularity           object
release_date         object
revenue              object
runtime              object
status               object
tagline              object
title                object
vote_average         object
vote_count           object
genres               object
dtype: object

* Columna 'budget'.

Tipo incorrecto.

In [340]:
movies['budget'].dtype

dtype('O')

Se cambia el tipo a int64.

In [341]:
movies['budget'] = movies['budget'].astype(
    'int64')

Se ha cambiado el tipo.

In [342]:
movies['budget'].dtype

dtype('int64')

* Columna 'popularity'.

Tipo incorrecto.

In [343]:
movies['popularity'].dtype

dtype('O')

Se cambia el tipo a float64.

In [344]:
movies['popularity'] = movies['popularity'].astype(
    'float64')

Se ha cambiado el tipo.

In [345]:
movies['popularity'].dtype

dtype('float64')

* Columna 'revenue'.

Tipo incorrecto.

In [346]:
movies['revenue'].dtype

dtype('O')

Se cambia el tipo a int64.

In [347]:
movies['revenue'] = movies['revenue'].astype(
    'int64')

Se ha cambiado el tipo.

In [348]:
movies['revenue'].dtype

dtype('int64')

* Columna 'runtime'.

Tipo incorrecto.

In [349]:
movies['runtime'].dtype

dtype('O')

Se cambia el tipo a float64.

In [350]:
movies['runtime'] = movies['runtime'].astype(
    'float64')

Se ha cambiado el tipo.

In [351]:
movies['runtime'].dtype

dtype('float64')

* Columna 'vote_average'.

Tipo incorrecto.

In [352]:
movies['vote_average'].dtype

dtype('O')

Se cambia el tipo a float64.

In [353]:
movies['vote_average'] = movies['vote_average'].astype(
    'float64')

Se ha cambiado el tipo.

In [354]:
movies['vote_average'].dtype

dtype('float64')

* Columna 'vote_count'.

Tipo incorrecto.

In [355]:
movies['vote_count'].dtype

dtype('O')

Se cambia el tipo a int64.

In [356]:
movies['vote_count'] = movies['vote_count'].astype(
    'int64')

Se ha cambiado el tipo.

In [357]:
movies['vote_count'].dtype

dtype('int64')

Tipos de las columnas.

In [358]:
movies.dtypes

budget                 int64
movie_id              object
original_language     object
overview              object
popularity           float64
release_date          object
revenue                int64
runtime              float64
status                object
tagline               object
title                 object
vote_average         float64
vote_count             int64
genres                object
dtype: object

### Las columnas 'revenue' y 'budget' estan completas

Columna 'revenue'.

In [359]:
movies['revenue'].isnull().sum()

0

Columna 'budget'.

In [360]:
movies['budget'].isnull().sum()

0

### La columna 'release_date' esta completa

In [361]:
movies['release_date'].isnull().sum()

0

### Crear la columna 'release_year'

Se extrae el año de la columna 'release_date' en la nueva columna 'release_year'.

In [362]:
movies['release_year'] = pd.to_datetime(
    movies['release_date']
    ).dt.year.astype(str)

El año fue extraído correctamente.

In [363]:
movies.iloc[0]['release_year']

'1995'

### Crear la columna 'return'

Gran parte de los datos son cero en las columnas 'revenue' y 'budget'.

In [364]:
movies['revenue'].value_counts()[0]

37949

In [365]:
movies['budget'].value_counts()[0]

36470

Se crea una variable que divide el valor de la columna 'revenue' por el valor de la columna 'budget' siempre que ambos valores sean mayores a cero.

In [366]:
return_movie = (
    lambda row: 
        row['revenue'] 
        / row['budget'] 
    if row['revenue'] > 0 
    and row['budget'] > 0 
    else 0)

Se crea la columna 'return' asignandole la anterior operación.

In [367]:
movies['return'] = movies.apply(
       return_movie, 
       axis=1).round(2)

La columna 'return' fue creada.

In [368]:
'return' in movies.columns

True

### Resetear el índice

El índice actual.

In [369]:
movies.index

Int64Index([    0,     1,     2,     3,     4,     5,     6,     7,     8,
                9,
            ...
            45425, 45426, 45427, 45428, 45429, 45430, 45432, 45433, 45434,
            45435],
           dtype='int64', length=45346)

El índice está incorrecto. No coincide con la cantidad de filas.

In [370]:
movies.shape

(45346, 16)

Se resetea el índice.

In [371]:
movies.reset_index(
    drop=True, 
    inplace=True
    )

El índice esta correcto.

In [372]:
movies.index

RangeIndex(start=0, stop=45346, step=1)

### Última revisión

Se explora el dataframe.

In [373]:
movies

,budget,movie_id,original_language,overview,popularity,release_date,revenue,runtime,status,tagline,title,vote_average,vote_count,genres,release_year,return
0,30000000,862,en,"Led by Woody, Andy's toys live happily in his ...",21.946943,1995-10-30,373554033,81.0,Released,None,Toy Story,7.7,5415,"[Animation, Comedy, Family]",1995,12.45
1,65000000,8844,en,When siblings Judy and Peter discover an encha...,17.015539,1995-12-15,262797249,104.0,Released,Roll the dice and unleash the excitement!,Jumanji,6.9,2413,"[Adventure, Fantasy, Family]",1995,4.04
2,0,15602,en,A family wedding reignites the ancient feud be...,11.712900,1995-12-22,0,101.0,Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,6.5,92,"[Romance, Comedy]",1995,0.00
3,16000000,31357,en,"Cheated on, mistreated and stepped on, the wom...",3.859495,1995-12-22,81452156,127.0,Released,Friends are the people who let you be yourself...,Waiting to Exhale,6.1,34,"[Comedy, Drama, Romance]",1995,5.09
4,0,11862,en,Just when George Banks has recovered from his ...,8.387519,1995-02-10,76578911,106.0,Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,5.7,173,[Comedy],1995,0.00
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45341,0,30840,en,"Yet another version of the classic epic, with ...",5.683753,1991-05-13,0,104.0,Released,None,Robin Hood,5.7,26,"[Drama, Action, Romance]",1991,0.00
45342,0,111109,tl,An artist struggles to finish his work while a...,0.178241,2011-11-17,0,360.0,Released,None,Century of Birthing,9.0,3,[Drama],2011,0.00
45343,0,67758,en,"When one of her hits goes wrong, a professiona...",0.903007,2003-08-01,0,90.0,Released,A deadly game of wits.,Betrayal,3.8,6,"[Action, Drama, Thriller]",2003,0.00
45344,0,227506,en,"In a small town live two brothers, one a minis...",0.003503,1917-10-21,0,87.0,Released,None,Satan Triumphant,0.0,0,[Unknown],1917,0.00
45345,0,461257,en,50 years after decriminalisation of homosexual...,0.163015,2017-06-09,0,75.0,Released,None,Queerama,0.0,0,[Unknown],2017,0.00

Se obtiene una información general.

In [374]:
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45346 entries, 0 to 45345
Data columns (total 16 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   budget             45346 non-null  int64
 1   movie_id           45346 non-null  object
 2   original_language  45335 non-null  object
 3   overview           44405 non-null  object
 4   popularity         45346 non-null  float64
 5   release_date       45346 non-null  object
 6   revenue            45346 non-null  int64
 7   runtime            45100 non-null  float64
 8   status             45266 non-null  object
 9   tagline            20387 non-null  object
 10  title              45346 non-null  object
 11  vote_average       45346 non-null  float64
 12  vote_count         45346 non-null  int64
 13  genres             45346 non-null  object
 14  release_year       45346 non-null  object
 15  return             45346 non-null  float64
dtypes: float64(4), int64(3), object(9)
memory usage: 5.5+ MB

## Carga

In [375]:
ruta_actual = os.getcwd()

ruta_actual

'c:\\Users\\franc\\Desktop\\Proyecto_Peliculas\\notebooks\\ETL'

In [376]:
ruta_del_proyecto = os.path.dirname(
    os.path.dirname(ruta_actual)
    )

ruta_del_proyecto

'c:\\Users\\franc\\Desktop\\Proyecto_Peliculas'

In [377]:
ruta_a_exportar = os.path.join(
    ruta_del_proyecto, 
    'data', 
    'movies.parquet'
    )

ruta_a_exportar

'c:\\Users\\franc\\Desktop\\Proyecto_Peliculas\\data\\movies.parquet'

In [378]:
movies.to_parquet(ruta_a_exportar)

In [379]:
del movies
gc.collect()

144